import Head from 'next/head';

import { useIntl } from 'react-intl';

import Search from '@/components/Search';

export default function Home() {
  const { formatMessage: t } = useIntl();
  return (
    <>
      <Head>
        <title>Moto Aunt</title>
        <meta content='Generated by create next app' name='description' />
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <main>
        <h1 className='text-center text-4xl text-blue-900 text-bold mb-16 mt-8'>
          {t({ id: 'home.title' })}
        </h1>
        <div className='flex justify-center'>
          <Search />
        </div>
      </main>
    </>
  );
}
