import { gql, useQuery } from '@apollo/client';
import { Card } from 'flowbite-react';
import Head from 'next/head';

const ALL_BIKES_QUERY = gql`
  query allBikesQuery {
    bikes {
      id
      make
      model
      year
      type
    }
  }
`;

export default function Home() {
  const { data, error, loading } = useQuery(ALL_BIKES_QUERY);

  console.log(data, error, loading);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content='Generated by create next app' name='description' />
        <meta content='width=device-width, initial-scale=1' name='viewport' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <main>
        <div>
          <Card href='#'>
            <h5 className='text-2xl font-bold tracking-tight text-gray-900 dark:text-white'>
              Main Page
            </h5>
            <p className='font-normal text-gray-700 dark:text-gray-400'>Main page Content</p>
          </Card>
        </div>
      </main>
    </>
  );
}
